const tours = [
  {
    date: 6,
    month: "janurary",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 8,
    month: "janurary",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 24,
    month: "janurary",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 26,
    month: "janurary",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 20,
    month: "march",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 22,
    month: "march",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 1,
    month: "April",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 2,
    month: "april",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 6,
    month: "april",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 8,
    month: "april",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 10,
    month: "may",
    year: 2025,
    location: "",
    country: "",
    availableTickets: true,
  },
  {
    date: 11,
    month: "may",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 20,
    month: "may",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 22,
    month: "may",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 5,
    month: "june",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 7,
    month: "june",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 8,
    month: "june",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 15,
    month: "june",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 17,
    month: "june",
    year: 2025,
    location: "",
    country: "",
    availableTickets: true,
  },
  {
    date: 20,
    month: "june",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 22,
    month: "june",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 1,
    month: "july",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 5,
    month: "july",
    year: 2025,
    location: "",
    country: "",
    availableTickets: true,
  },
  {
    date: 6,
    month: "july",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 8,
    month: "july",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 29,
    month: "july",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 30,
    month: "july",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 3,
    month: "august",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 4,
    month: "august",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 10,
    month: "august",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 11,
    month: "august",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 2,
    month: "september",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 8,
    month: "september",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 10,
    month: "september",
    year: 2025,
    location: "",
    country: "",
    availableTickets: true,
  },
  {
    date: 16,
    month: "september",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
  {
    date: 1,
    month: "october",
    year: 2025,
    location: "",
    country: "",
    availableTickets: true,
  },
  {
    date: 3,
    month: "october",
    year: 2025,
    location: "",
    country: "",
    availableTickets: false,
  },
];
